/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.62.0
  Forc version: 0.44.0
  Fuel-Core version: 0.20.6
*/

import type {
  BigNumberish,
  BN,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

export type AccrueInvitationsEventInput = { address: AddressInput, invites_amount: BigNumberish, nasted_max_invites: BigNumberish };
export type AccrueInvitationsEventOutput = { address: AddressOutput, invites_amount: BN, nasted_max_invites: BN };
export type AddressInput = { value: string };
export type AddressOutput = AddressInput;
export type CheckinEventInput = { address: AddressInput, referal: AddressInput };
export type CheckinEventOutput = { address: AddressOutput, referal: AddressOutput };

export type ReferalContractAbiConfigurables = {
  OWNER: AddressInput;
};

interface ReferalContractAbiInterface extends Interface {
  functions: {
    accrue_invitations: FunctionFragment;
    add_admin: FunctionFragment;
    chekin: FunctionFragment;
    remove_admin: FunctionFragment;
    verify: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'accrue_invitations', values: [AddressInput, BigNumberish, BigNumberish]): Uint8Array;
  encodeFunctionData(functionFragment: 'add_admin', values: [AddressInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'chekin', values: [AddressInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'remove_admin', values: [AddressInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'verify', values: [AddressInput]): Uint8Array;

  decodeFunctionData(functionFragment: 'accrue_invitations', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'add_admin', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'chekin', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'remove_admin', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'verify', data: BytesLike): DecodedValue;
}

export class ReferalContractAbi extends Contract {
  interface: ReferalContractAbiInterface;
  functions: {
    accrue_invitations: InvokeFunction<[address: AddressInput, invites_amount: BigNumberish, nasted_max_invites: BigNumberish], void>;
    add_admin: InvokeFunction<[address: AddressInput], void>;
    chekin: InvokeFunction<[referal_address: AddressInput], boolean>;
    remove_admin: InvokeFunction<[address: AddressInput], void>;
    verify: InvokeFunction<[address: AddressInput], [BN, BN]>;
  };
}
