/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.69.1
  Forc version: 0.46.1
  Fuel-Core version: 0.20.8
*/

import type {
  BigNumberish,
  BN,
  Bytes,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

import type { Enum, Vec } from "./common";

export enum ErrorInput { TradingIsPaused = 'TradingIsPaused', InvalidAsset = 'InvalidAsset', AccessDenied = 'AccessDenied', NotEnoughFreeCollateral = 'NotEnoughFreeCollateral', OnlyClearingHouse = 'OnlyClearingHouse', InvalidPythFeePayment = 'InvalidPythFeePayment' }
export enum ErrorOutput { TradingIsPaused = 'TradingIsPaused', InvalidAsset = 'InvalidAsset', AccessDenied = 'AccessDenied', NotEnoughFreeCollateral = 'NotEnoughFreeCollateral', OnlyClearingHouse = 'OnlyClearingHouse', InvalidPythFeePayment = 'InvalidPythFeePayment' }
export enum PauseErrorInput { Paused = 'Paused', NotPaused = 'NotPaused' }
export enum PauseErrorOutput { Paused = 'Paused', NotPaused = 'NotPaused' }
export enum ReentrancyErrorInput { NonReentrant = 'NonReentrant' }
export enum ReentrancyErrorOutput { NonReentrant = 'NonReentrant' }

export type AddressInput = { value: string };
export type AddressOutput = AddressInput;
export type AssetIdInput = { value: string };
export type AssetIdOutput = AssetIdInput;
export type CollateralChangeEventInput = { trader: AddressInput, collateral: BigNumberish };
export type CollateralChangeEventOutput = { trader: AddressOutput, collateral: BN };
export type I64Input = { value: BigNumberish, negative: boolean };
export type I64Output = { value: BN, negative: boolean };
export type RawBytesInput = { ptr: BigNumberish, cap: BigNumberish };
export type RawBytesOutput = { ptr: BN, cap: BN };

export type VaultAbiConfigurables = {
  OWNER: AddressInput;
  PROXY_ADDRESS: AddressInput;
  SETTLEMENT_TOKEN: AssetIdInput;
};

interface VaultAbiInterface extends Interface {
  functions: {
    add_admin: FunctionFragment;
    deposit_collateral: FunctionFragment;
    get_account_value_and_total_collateral_value: FunctionFragment;
    get_collateral_balance: FunctionFragment;
    get_free_collateral: FunctionFragment;
    pause_trading: FunctionFragment;
    remove_admin: FunctionFragment;
    resume_trading: FunctionFragment;
    withdraw_all: FunctionFragment;
    withdraw_collateral: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'add_admin', values: [AddressInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'deposit_collateral', values: []): Uint8Array;
  encodeFunctionData(functionFragment: 'get_account_value_and_total_collateral_value', values: [AddressInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'get_collateral_balance', values: [AddressInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'get_free_collateral', values: [AddressInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'pause_trading', values: []): Uint8Array;
  encodeFunctionData(functionFragment: 'remove_admin', values: [AddressInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'resume_trading', values: []): Uint8Array;
  encodeFunctionData(functionFragment: 'withdraw_all', values: [Vec<Bytes>]): Uint8Array;
  encodeFunctionData(functionFragment: 'withdraw_collateral', values: [BigNumberish, Vec<Bytes>]): Uint8Array;

  decodeFunctionData(functionFragment: 'add_admin', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'deposit_collateral', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_account_value_and_total_collateral_value', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_collateral_balance', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_free_collateral', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'pause_trading', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'remove_admin', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'resume_trading', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'withdraw_all', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'withdraw_collateral', data: BytesLike): DecodedValue;
}

export class VaultAbi extends Contract {
  interface: VaultAbiInterface;
  functions: {
    add_admin: InvokeFunction<[address: AddressInput], void>;
    deposit_collateral: InvokeFunction<[], void>;
    get_account_value_and_total_collateral_value: InvokeFunction<[trader: AddressInput], [I64Output, I64Output]>;
    get_collateral_balance: InvokeFunction<[address: AddressInput], BN>;
    get_free_collateral: InvokeFunction<[trader: AddressInput], I64Output>;
    pause_trading: InvokeFunction<[], void>;
    remove_admin: InvokeFunction<[address: AddressInput], void>;
    resume_trading: InvokeFunction<[], void>;
    withdraw_all: InvokeFunction<[price_update_data: Vec<Bytes>], BN>;
    withdraw_collateral: InvokeFunction<[amount: BigNumberish, price_update_data: Vec<Bytes>], void>;
  };
}
