/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.77.0
  Forc version: 0.51.1
  Fuel-Core version: 0.22.1
*/

export type { ProxyAbi } from './ProxyAbi';

export { ProxyAbi__factory } from './factories/ProxyAbi__factory';
