/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.62.0
  Forc version: 0.44.0
  Fuel-Core version: 0.20.6
*/

export type { SpotMarketAbi } from "./SpotMarketAbi";
export type { TokenFactoryAbi } from "./TokenFactoryAbi";
export type { OracleAbi } from "./OracleAbi";

export { SpotMarketAbi__factory } from "./factories/SpotMarketAbi__factory";
export { TokenFactoryAbi__factory } from "./factories/TokenFactoryAbi__factory";
export { OracleAbi__factory } from "./factories/OracleAbi__factory";
