/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.62.0
  Forc version: 0.44.0
  Fuel-Core version: 0.20.6
*/

export type { SpotMarketAbi } from './SpotMarketAbi';

export { SpotMarketAbi__factory } from './factories/SpotMarketAbi__factory';
