/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.69.1
  Forc version: 0.46.1
  Fuel-Core version: 0.20.8
*/

export type { SpotMarketAbi } from './SpotMarketAbi';

export { SpotMarketAbi__factory } from './factories/SpotMarketAbi__factory';
