/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.39.1
  Forc version: 0.35.5
  Fuel-Core version: 0.17.3
*/

export type { SpotMarketAbi } from './SpotMarketAbi';

export { SpotMarketAbi__factory } from './factories/SpotMarketAbi__factory';
